feat: Add ASDF_RUST_IGNORE_COMPONENTS
\#\# Description
Currently there's no way to skip installation of the docs (as well as
other components).
While helpful in general, on systems with a small amount of storage
(e.g. 128/256 GB) those megabytes can be a dealbreaker.
For the most recent stable version (1.51.0) it takes around __40%__ out
of
total space for the installation (__418/1145 MB__).

\#\# Proposal
This PR introduces `ASDF_RUST_IGNORE_COMPONENTS` which is being passed
as
a value of option `--without` to the Rust `install` script. This option
takes comma-separated list of components to skip during installation
(e.g. `rust-docs,miri-preview` to skip installation of docs and MIRI
preview)

\#\# Results
It greatly helps to save storage space.
As a side effect, it drastically decreases installation time: on my
machine, doc building takes a handful of time: __20/23 minutes__ of
installation (downloading + actual installation) was spent __building
docs__ I won't need.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -31,6 +31,11 @@ install_rust() {
     fail "asdf-rust supports release installs only"
   fi
 
+  local install_extra_flags=''
+  if [ -n "${ASDF_RUST_IGNORE_COMPONENTS}" ]; then
+    install_extra_flags="--without=${ASDF_RUST_IGNORE_COMPONENTS} $install_extra_flags"
+  fi
+
   local platform
 
   case "$OSTYPE" in
@@ -67,7 +72,7 @@ install_rust() {
 
     echo "∗ Installing..."
     cd "$distination_path"
-    ./install.sh --prefix="$install_path" || fail "Could not install"
+    ./install.sh --prefix="$install_path" $install_extra_flags || fail "Could not install"
 
     rm -rf "$tmp_download_dir"
 
